import { _electron as electron } from '../android/chat-ui/node_modules/playwright/index.mjs';
import path from 'node:path';
import { mkdtemp, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
const server = createServer((request, response) => {
  assert.equal(request.url, '/v1/models');
  assert.equal(request.headers.authorization, 'Bearer DESKTOP_TEST_KEY');
  response.setHeader('Content-Type', 'application/json');
  response.end(JSON.stringify({ data: [{ id: 'mock', context_length: 24000 }] }));
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const data = process.env.BBUI_TEST_DATA || await mkdtemp(path.resolve('runs/desktop-window-'));
const env = { ...process.env, BBUI_DESKTOP_DATA: data }; delete env.ELECTRON_RUN_AS_NODE;
const application = await electron.launch({ executablePath: process.argv[2] || path.resolve('node_modules/electron/dist/electron.exe'), args: process.argv[2] ? [] : [path.resolve('.desktop/app')], env, timeout: 30000 });
const mainPid = await application.evaluate(() => process.pid);
application.process().stderr.on('data', data => console.error(String(data)));
application.on('console', message => console.log('Electron:', message.text()));
console.log('Launched', data);
try {
  const page = await application.firstWindow();
  page.setDefaultTimeout(35000);
  page.on('pageerror', error => console.error(error.message));
  await page.getByRole('heading', { name: 'BigBirdUI · 大鸟手机助手' }).waitFor();
  assert.equal(await page.locator('.chat-shell,.phone-pane').count(), 0);
  assert.equal(await page.getByRole('button', { name: '开始使用', exact: true }).isDisabled(), true);
  await page.screenshot({ path: path.join(data, 'window.png') });
  await page.getByRole('button', { name: '添加模型', exact: true }).click();
  await page.getByRole('dialog', { name: '设置' }).waitFor();
  await page.getByRole('button', { name: '模型', exact: true }).click();
  await page.getByRole('button', { name: '添加连接', exact: true }).click();
  await page.getByLabel('名称', { exact: true }).fill('本地模拟');
  await page.getByLabel('配置预设', { exact: true }).selectOption('openrouter');
  assert.equal(await page.getByLabel('API 地址', { exact: true }).inputValue(), 'https://openrouter.ai/api/v1');
  await page.getByLabel('API 地址', { exact: true }).fill(`http://127.0.0.1:${server.address().port}/v1`);
  await page.getByLabel('API 密钥', { exact: true }).fill('DESKTOP_TEST_KEY');
  assert.equal(await page.getByLabel('模型 ID', { exact: true }).count(), 0);
  await page.getByRole('button', { name: '保存设置' }).click();
  await page.getByRole('status').filter({ hasText: '已完成' }).waitFor();
  await page.getByRole('button', { name: '发现模型' }).click();
  await page.getByLabel('模型 ID', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('模型 ID', { exact: true }).inputValue(), 'mock');
  await page.getByText('模型能力设置', { exact: true }).click();
  assert.equal(await page.getByLabel('图片输入', { exact: true }).inputValue(), '');
  assert.equal(await page.getByLabel('上下文长度（K）', { exact: true }).inputValue(), '24');
  await page.getByLabel('图片输入', { exact: true }).selectOption('true');
  await page.getByLabel('思考能力', { exact: true }).selectOption('true');
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 0);
  await page.getByLabel('上下文长度（K）', { exact: true }).fill('32');
  await page.getByLabel('最大输出长度（K）', { exact: true }).fill('8.192');
  await page.getByRole('button', { name: '发现模型' }).click();
  assert.equal(await page.getByLabel('上下文长度（K）', { exact: true }).inputValue(), '32');
  await page.getByRole('button', { name: '设为默认' }).click();
  await page.getByRole('button', { name: '保存设置' }).click();
  await page.getByRole('status').filter({ hasText: '已完成' }).waitFor();
  assert.ok(!(await readFile(path.join(data, 'settings.json'), 'utf8')).includes('DESKTOP_TEST_KEY'));
  await page.waitForFunction(async () => (await window.Desktop.invoke('settings')).connections[0].models[0]?.contextWindow === 32000);
  const saved = await page.evaluate(() => window.Desktop.invoke('settings'));
  assert.equal(saved.connections[0].models[0].contextWindow, 32000);
  assert.equal(saved.connections[0].models[0].maxTokens, 8192);
  assert.equal(saved.connections[0].models[0].thinkingLevels, undefined);
  assert.equal(saved.connections[0].models[0].reasoning, true);
  await page.getByRole('button', { name: '完成', exact: true }).click();
  await page.getByRole('dialog', { name: '设置' }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '管理模型', exact: true }).click();
  await page.getByText('模型能力设置', { exact: true }).click();
  assert.equal(await page.getByLabel('图片输入', { exact: true }).inputValue(), 'true');
  assert.equal(await page.getByLabel('上下文长度（K）', { exact: true }).inputValue(), '32');
  assert.equal(await page.getByLabel('最大输出长度（K）', { exact: true }).inputValue(), '8.192');
  await page.screenshot({ path: path.join(data, 'settings.png') });
  console.log('Electron sandboxed welcome, settings and safeStorage: PASS');
} finally {
  server.closeAllConnections(); server.close();
  // Crash path; normal close is verified without an attached inspector separately.
  process.kill(mainPid, 'SIGKILL');
  await new Promise(resolve => application.once('close', resolve));
}
