// One geometric source for web SVGs, Android vectors and export assets.
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from '../../android/chat-ui/node_modules/playwright/index.mjs';

const body = 'M380 303C454 208 522 149 590 155C675 154 728 217 724 270L722 293L755 337Q758 344 750 343L694 334Q665 363 668 392L672 441L689 436L705 399Q710 385 725 386L785 390Q805 390 800 409L764 529C736 617 646 682 561 704C428 744 321 690 283 586C251 485 292 387 380 303Z';
const eye = 'M664 282A16 16 0 1 0 632 282A16 16 0 1 0 664 282Z';
const speaker = 'M741 400L762 401Q768 401 767 406Q767 412 761 412L740 411Q734 411 735 405Q735 400 741 400Z';
const wing = 'M588 468C615 496 658 512 692 510C708 509 722 504 730 497Q733 494 730 491Q727 488 724 492C713 501 696 503 680 503C645 502 613 486 595 464Q592 461 589 464Q587 466 588 468Z';
const full = [body, eye, speaker, wing].join('');
// At notification/avatar sizes a wider crease and earpiece survive rasterization.
const smallWing = 'M585 470C615 500 658 516 693 514C710 513 725 507 733 499Q738 494 733 489Q728 484 723 489C711 498 695 500 680 499C647 498 616 482 599 461Q594 456 588 460Q582 464 585 470Z';
const smallSpeaker = 'M741 397L762 398Q772 398 770 407Q769 415 760 415L739 414Q730 414 732 405Q733 396 741 397Z';
const small = [body, eye, smallSpeaker, smallWing].join('');
const root = new URL('../../', import.meta.url);
async function save(path, text) { const url = new URL(path, root); await mkdir(new URL('./', url), { recursive: true }); await writeFile(url, text); }
const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><rect width="108" height="108" rx="25" fill="#2D513E"/><path transform="translate(-18.9 -5.4) scale(.135)" fill="#F7F6EF" fill-rule="evenodd" d="${full}"/></svg>`;
await save('android/chat-ui/src/brand.tsx', `// Generated by design/brand/generate.mjs; edit the shared source there.\nexport function BrandMark({ className = '', small = false }: { className?: string; small?: boolean }) {\n  return <svg className={className} viewBox="0 0 600 640" fill="currentColor" aria-hidden="true" focusable="false"><path transform="translate(-240 -120)" fillRule="evenodd" d={small ? '${small}' : '${full}'} /></svg>;\n}\n`);
await save('android/chat-ui/public/brand.svg', icon);
const vector = (path, color, viewport, group, size) => `<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="${size}dp" android:height="${size}dp" android:viewportWidth="${viewport[0]}" android:viewportHeight="${viewport[1]}">\n    <group ${group}><path android:fillColor="${color}" android:fillType="evenOdd" android:pathData="${path}" /></group>\n</vector>\n`;
const res = 'android/app/src/main/res/';
await save(res + 'drawable/ic_bbui_mark.xml', vector(full, '#2D513E', [600,640], 'android:translateX="-240" android:translateY="-120"', 64));
await save(res + 'drawable/ic_bbui_notification.xml', vector(small, '#FFFFFFFF', [600,640], 'android:translateX="-240" android:translateY="-120"', 24));
await save(res + 'drawable/ic_bbui_foreground.xml', vector(full, '#F7F6EF', [108,108], 'android:scaleX="0.1" android:scaleY="0.1" android:translateY="10"', 108));
await save(res + 'drawable/ic_bbui_monochrome.xml', vector(small, '#FFFFFFFF', [108,108], 'android:scaleX="0.1" android:scaleY="0.1" android:translateY="10"', 108));
const adaptive = mono => `<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n    <background android:drawable="@color/bbui_icon_background" />\n    <foreground android:drawable="@drawable/ic_bbui_foreground" />${mono ? '\n    <monochrome android:drawable="@drawable/ic_bbui_monochrome" />' : ''}\n</adaptive-icon>\n`;
await save(res + 'drawable/ic_bbui.xml', adaptive(false));
await save(res + 'drawable-v33/ic_bbui.xml', adaptive(true));
await save(res + 'values/brand.xml', '<resources>\n    <color name="bbui_icon_background">#2D513E</color>\n</resources>\n');

const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const page = await browser.newPage({ deviceScaleFactor: 1 });
  for (const size of [16, 24, 32, 48, 64, 128, 256]) {
    await page.setViewportSize({ width: size, height: size });
    const artwork = size < 48 ? icon.replace(full, small) : icon;
    await page.setContent(`<style>body{margin:0}svg{width:100vw;height:100vh;display:block}</style>${artwork}`);
    const output = new URL(`design/brand/png/bbui-app-icon-${size}.png`, root);
    await mkdir(new URL('./', output), { recursive: true });
    await page.screenshot({ path: fileURLToPath(output), omitBackground: true });
  }
} finally { await browser.close(); }
