// One geometric source for web SVGs, Android vectors and export assets.
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from '../../android/chat-ui/node_modules/playwright/index.mjs';

const body = 'M380 303C454 208 522 149 590 155C675 154 728 217 724 270L722 293L755 337Q758 344 750 343L694 334Q665 363 668 392L672 441L689 436L705 399Q710 385 725 386L785 390Q805 390 800 409L764 529C736 617 646 682 561 704C428 744 321 690 283 586C251 485 292 387 380 303Z';
const eye = 'M664 282A16 16 0 1 0 632 282A16 16 0 1 0 664 282Z';
const speaker = 'M741 400L762 401Q768 401 767 406Q767 412 761 412L740 411Q734 411 735 405Q735 400 741 400Z';
const wing = 'M588 468C615 496 658 512 692 510C708 509 722 504 730 497Q733 494 730 491Q727 488 724 492C713 501 696 503 680 503C645 502 613 486 595 464Q592 461 589 464Q587 466 588 468Z';
const full = [body, eye, speaker, wing].join('');
// At notification/avatar sizes a wider crease and earpiece survive rasterization.
const smallWing = 'M585 470C615 500 658 516 693 514C710 513 725 507 733 499Q738 494 733 489Q728 484 723 489C711 498 695 500 680 499C647 498 616 482 599 461Q594 456 588 460Q582 464 585 470Z';
const smallSpeaker = 'M741 397L762 398Q772 398 770 407Q769 415 760 415L739 414Q730 414 732 405Q733 396 741 397Z';
const small = [body, eye, smallSpeaker, smallWing].join('');
const root = new URL('../../', import.meta.url);
async function save(path, text) { const url = new URL(path, root); await mkdir(new URL('./', url), { recursive: true }); await writeFile(url, text); }
const mark = (color, compact = false) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 640" fill="${color}"><path transform="translate(-240 -120)" fill-rule="evenodd" d="${compact ? small : full}"/></svg>`;
const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><rect width="108" height="108" rx="25" fill="#2D513E"/><path transform="translate(-18.9 -5.4) scale(.135)" fill="#F7F6EF" fill-rule="evenodd" d="${full}"/></svg>`;
const avatar = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><circle cx="54" cy="54" r="54" fill="#D6DFCB"/><path transform="translate(-18.9 -5.4) scale(.135)" fill="#2D513E" fill-rule="evenodd" d="${full}"/></svg>`;
const letterB = 'M8 10Q8 6 12 6H23Q27 6 27 10V40C32 35 39 32 47 32C65 32 78 46 78 65C78 84 65 98 46 98C23 98 8 84 8 63ZM27 65C27 76 34 83 44 83C54 83 61 76 61 65C61 54 54 47 44 47C34 47 27 54 27 65Z';
const letters = `<g fill="#2D513E" fill-rule="evenodd"><path d="${letterB}"/><path transform="translate(82)" d="${letterB}"/><path d="M174 36H191V68Q191 82 204 82Q217 82 217 68V36H234V68Q234 98 204 98Q174 98 174 68Z"/><path d="M247 36H264V96H247ZM264 15A9 9 0 1 0 246 15A9 9 0 1 0 264 15Z"/></g>`;
await save('design/brand/bbui-mark.svg', mark('#2D513E'));
await save('design/brand/bbui-mark-light.svg', mark('#F7F6EF'));
await save('design/brand/bbui-mark-mono.svg', mark('#000000'));
await save('design/brand/bbui-mark-small.svg', mark('#2D513E', true));
await save('design/brand/bbui-app-icon.svg', icon);
await save('design/brand/bbui-avatar.svg', avatar);
await save('design/brand/bbui-wordmark.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 272 104">${letters}</svg>`);
await save('design/brand/bbui-lockup.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 418 128"><path transform="translate(-48 -24) scale(.2)" fill="#2D513E" fill-rule="evenodd" d="${full}"/><g transform="translate(143 12)">${letters}</g></svg>`);
await save('android/chat-ui/src/brand.tsx', `// Generated by design/brand/generate.mjs; edit the shared source there.\nexport function BrandMark({ className = '', small = false }: { className?: string; small?: boolean }) {\n  return <svg className={className} viewBox="0 0 600 640" fill="currentColor" aria-hidden="true" focusable="false"><path transform="translate(-240 -120)" fillRule="evenodd" d={small ? '${small}' : '${full}'} /></svg>;\n}\n`);
await save('android/chat-ui/public/brand.svg', icon);
const vector = (path, color, viewport, group, size) => `<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="${size}dp" android:height="${size}dp" android:viewportWidth="${viewport[0]}" android:viewportHeight="${viewport[1]}">\n    <group ${group}><path android:fillColor="${color}" android:fillType="evenOdd" android:pathData="${path}" /></group>\n</vector>\n`;
const res = 'android/app/src/main/res/';
await save(res + 'drawable/ic_bbui_mark.xml', vector(full, '#2D513E', [600,640], 'android:translateX="-240" android:translateY="-120"', 64));
await save(res + 'drawable/ic_bbui_notification.xml', vector(small, '#FFFFFFFF', [600,640], 'android:translateX="-240" android:translateY="-120"', 24));
await save(res + 'drawable/ic_bbui_foreground.xml', vector(full, '#F7F6EF', [108,108], 'android:scaleX="0.1" android:scaleY="0.1" android:translateY="10"', 108));
await save(res + 'drawable/ic_bbui_monochrome.xml', vector(small, '#FFFFFFFF', [108,108], 'android:scaleX="0.1" android:scaleY="0.1" android:translateY="10"', 108));
const adaptive = mono => `<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n    <background android:drawable="@color/bbui_icon_background" />\n    <foreground android:drawable="@drawable/ic_bbui_foreground" />${mono ? '\n    <monochrome android:drawable="@drawable/ic_bbui_monochrome" />' : ''}\n</adaptive-icon>\n`;
await save(res + 'drawable/ic_bbui.xml', adaptive(false));
await save(res + 'drawable-v33/ic_bbui.xml', adaptive(true));
await save(res + 'values/brand.xml', '<resources>\n    <color name="bbui_icon_background">#2D513E</color>\n</resources>\n');

const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const page = await browser.newPage({ deviceScaleFactor: 1 });
  for (const [name, svg] of [['mark', mark('#2D513E')], ['app-icon', icon], ['avatar', avatar]]) {
    for (const size of name === 'app-icon' ? [1024, 512, 256, 192, 128, 64, 48, 32, 24, 16] : [1024, 512, 192, 48]) {
      await page.setViewportSize({ width: size, height: size });
      const artwork = name === 'app-icon' && size < 48 ? icon.replace(full, small) : svg;
      await page.setContent(`<style>body{margin:0}svg{width:100vw;height:100vh;display:block}</style>${artwork}`);
      const path = new URL(`design/brand/png/bbui-${name}-${size}.png`, root);
      await mkdir(new URL('./', path), { recursive: true });
      await page.screenshot({ path: fileURLToPath(path), omitBackground: true });
    }
  }
  await page.setViewportSize({ width: 1200, height: 820 });
  const board = `<style>*{box-sizing:border-box}body{margin:0;background:#F7F6EF;color:#2D513E;font:16px Arial,'Microsoft YaHei',sans-serif;padding:45px}header{letter-spacing:5px;font-size:17px}.layout{display:grid;grid-template-columns:1.25fr 1fr;gap:80px;margin-top:35px}.hero{width:460px;height:480px}.word{width:240px;height:95px;margin:0 auto;display:block}.samples{display:flex;gap:35px;align-items:center;flex-wrap:wrap}.tile{width:185px}.circle{width:150px}.caption{font-size:13px;letter-spacing:2px;margin:15px 0 28px}svg{width:100%;height:100%}.sizes{display:flex;gap:25px;align-items:center;margin-top:20px}.dark{background:#2D513E;padding:12px;border-radius:12px}.footer{border-top:1px solid #dae0d2;margin-top:25px;padding-top:20px;font-size:13px;line-height:1.8;color:#6a7c67}</style><header>BBUI / BIGBIRD</header><div class="layout"><div><div class="hero">${mark('#2D513E')}</div><div class="word"><svg viewBox="0 0 272 104">${letters}</svg></div></div><div><div class="samples"><div><div class="tile">${icon}</div><div class="caption">APP ICON</div></div><div><div class="circle">${avatar}</div><div class="caption">AVATAR</div></div></div><div class="caption">SMALL SIZES · 16 / 24 / 32 / 48</div><div class="sizes">${[16,24,32,48].map(size=>`<div style="width:${size}px;height:${size}px">${mark('#2D513E',true)}</div>`).join('')}<div class="dark" style="width:72px;height:72px">${mark('#F7F6EF',true)}</div></div><div class="footer">大鸟 · 小手机<br>无尾轮廓 / 轻弧线翅膀<br><br>主色 #2D513E<br>浅色 #F7F6EF<br>辅助色 #D6DFCB<br><br>SVG 矢量 / Android 自适应图标<br>单色 / 反白 / 小尺寸光学校正</div></div></div>`;
  await save('design/brand/preview.html', board);
  await page.setContent(board);
  await page.screenshot({ path: fileURLToPath(new URL('design/brand/preview.png', root)) });
} finally { await browser.close(); }
